### ISSUE TITLE
possibly incorrect OPAESIM_REPO_BRANCH variable value in build-opae.sh

### ISSUE THREAD

**Issue by umairsiddiqui-digitek** [OFS/oneapi-asp#139]
possibly incorrect OPAESIM_REPO_BRANCH variable value in build-opae.sh

https://github.com/OFS/oneapi-asp/blob/51ccd10edb739581ace2a00f02d2e0dd26e8041f/common/scripts/build-opae.sh#L124

```
    # Default branch to 'master' if the branch variable is not set
    if [ -z "${OPAESIM_REPO_BRANCH}" ]; then
        OPAESIM_REPO_BRANCH="release/2.5.0"
    fi
  ```
  
  but according to
  https://github.com/orgs/OFS/discussions/60  
  
  the branch/tag for 2024.1-1 release is 
  
 ```
opae-sim | release/2.12.0 | 2.12.0-1 

```

**Comment by cohensus** [comment]
Hi there,
Thanks for pointing this inconsistency out.  We are working with engineering team to correct this old version reference.  Will provide an update shortly.

**Comment by aktole** [comment]
Hi, 
Do you have the OFS_ASP_ENV_ENABLE_ASE and/or OPENCL_ASE_SIM variable set ? Please unset & retry the build. <br>Note: ASE flow is not supported for oneapi-asps in the [current release](https://github.com/OFS/oneapi-asp/releases). For environment variables to be set during build, please see pre-requisites section [here](https://ofs.github.io/ofs-2024.1-1/hw/common/user_guides/oneapi_asp/ug_oneapi_asp/#23-prerequisites).
