### ISSUE TITLE
build-asp.sh script checkout the master branch of ofs-platform-afu-bbb instead of release tag of ofs-platform-afu-bbb

### ISSUE THREAD

**Issue by umairsiddiqui-digitek** [OFS/oneapi-asp#157]
build-asp.sh script checkout the master branch of `ofs-platform-afu-bbb`:

https://github.com/OFS/oneapi-asp/blob/76ba584312fcc1e08c76407f26b2034d315fd53e/n6001/scripts/build-asp.sh#L72

it should checkout particular tag of `ofs-platform-afu-bbb` like  [ofs-2024.2-1](https://github.com/OFS/ofs-platform-afu-bbb/releases/tag/ofs-2024.2-1)

```

  if [ ! -d "$BUILD_DIR/ofs-platform-afu-bbb" ]; then
      # Default branch to 'master' if the branch variable is not set
      if [ -z "${OFS_PLATFORM_AFU_BBB_REPO_BRANCH}" ]; then
          OFS_PLATFORM_AFU_BBB_REPO_BRANCH="master"
      fi
      git clone https://github.com/OPAE/ofs-platform-afu-bbb.git -b ${OFS_PLATFORM_AFU_BBB_REPO_BRANCH} ofs-platform-afu-bbb || exit
  fi
  
```

**Comment by aktole** [comment]
Hi, 

Thank you for the notification, we have filed a case internally to fix. 

If the https://github.com/OFS/ofs-platform-afu-bbb has been cloned with correct tag for [PR tree generation (FIM compilation)](https://ofs.github.io/ofs-2024.2-1/hw/n6001/dev_guides/fim_dev/ug_dev_fim_ofs_n6001/#225-walkthrough-compile-ofs-fim), please set environment variable "OFS_PLATFORM_AFU_BBB" to point to this cloned directory as mentioned in pre-requisites [here](https://ofs.github.io/ofs-2024.2-1/hw/common/user_guides/oneapi_asp/ug_oneapi_asp/#23-prerequisites) for oneapi-asp setup.

Thank you.
