### ISSUE TITLE
oneapi-asp support for N6000 is missing

### ISSUE THREAD

**Issue by umairsiddiqui-digitek** [OFS/oneapi-asp#158]
the oneapi-asp support for N6000 is missing.

**Comment by aktole** [comment]
Hi, 

“ [The Intel® FPGA SmartNIC N6000-PL reference platform](https://www.intel.com/content/www/us/en/products/details/fpga/platforms/smartnic/n6000-pl-platform.html) has two configurations:
1. N6000-based SmartNIC with an Intel® Ethernet Controller E810 and bifurcated PCIe 4.0 x8 lanes to FPGA and x8
lanes to the Ethernet controller
2. N6001-based SmartNIC without an Ethernet controller
 
Shell Developer Guide for both variants: [Shell Developer Guide for Open FPGA Stack: Intel® FPGA SmartNIC N6000-PL / Intel® FPGA SmartNIC N6001-PL PCIe Attach](https://ofs.github.io/ofs-2024.2-1/hw/n6001/dev_guides/fim_dev/ug_dev_fim_ofs_n6001/)
 
The oneapi-asp lies in the PR (AFU) region and interfaces with the FIM using [PIM](https://ofs.github.io/ofs-2024.2-1/n6001/ug_dev_pim_based_afu/#21-pim-resources). The oneapi-asp provides a reference code for n6001 [here](https://github.com/OFS/oneapi-asp/tree/ofs-2024.2-1/n6001). The interfaces generated by oneapi compiler for oneapi kernel are controlled by the [board_spec.xml file](https://ofs.github.io/ofs-2024.2-1/hw/common/reference_manual/oneapi_asp/oneapi_asp_ref_mnl/#21-board_specxml-file) for board variant being compiled.
 
The reference oneapi-asp design is explained in [this](https://ofs.github.io/ofs-2024.2-1/hw/common/reference_manual/oneapi_asp/oneapi_asp_ref_mnl/#53-oneapi-asp-hardware-implementation) section. The reference code for [ofs_n6001 board variant](https://github.com/OFS/oneapi-asp/tree/master/n6001/hardware/ofs_n6001) interfaces with the host and on-board memory. The default n6000 FIM configuration does not have the Memory Subsystem enabled as explained [here](https://ofs.github.io/ofs-2024.2-1/hw/n6001/dev_guides/fim_dev/ug_dev_fim_ofs_n6001/#2125-memory-ofss-file). The steps to add the Memory-SS are given [here in the Shell Developer Guide](https://ofs.github.io/ofs-2024.2-1/hw/n6001/dev_guides/fim_dev/ug_dev_fim_ofs_n6001/#472-walkthrough-add-or-remove-the-memory-sub-system).
 
If you would like to compile for n6000, can you try generating the [PR tree for the FIM for n6000 configuration](https://ofs.github.io/ofs-2024.2-1/hw/n6001/dev_guides/fim_dev/ug_dev_fim_ofs_n6001/#225-walkthrough-compile-ofs-fim) with memory SS enabled, then using this PR build tree from FIM for building the oneapi-asp based on steps [here](https://ofs.github.io/ofs-2024.2-1/hw/common/user_guides/oneapi_asp/ug_oneapi_asp/)? ”

Thank you.

**Comment by aktole** [comment]
Hi, 

Following up on this issue. Do the comments provide guidance on the issue?

Thank you. 

> Hi,
> 
> “ [The Intel® FPGA SmartNIC N6000-PL reference platform](https://www.intel.com/content/www/us/en/products/details/fpga/platforms/smartnic/n6000-pl-platform.html) has two configurations:
> 
> 1. N6000-based SmartNIC with an Intel® Ethernet Controller E810 and bifurcated PCIe 4.0 x8 lanes to FPGA and x8
>    lanes to the Ethernet controller
> 2. N6001-based SmartNIC without an Ethernet controller
> 
> Shell Developer Guide for both variants: [Shell Developer Guide for Open FPGA Stack: Intel® FPGA SmartNIC N6000-PL / Intel® FPGA SmartNIC N6001-PL PCIe Attach](https://ofs.github.io/ofs-2024.2-1/hw/n6001/dev_guides/fim_dev/ug_dev_fim_ofs_n6001/)
> 
> The oneapi-asp lies in the PR (AFU) region and interfaces with the FIM using [PIM](https://ofs.github.io/ofs-2024.2-1/n6001/ug_dev_pim_based_afu/#21-pim-resources). The oneapi-asp provides a reference code for n6001 [here](https://github.com/OFS/oneapi-asp/tree/ofs-2024.2-1/n6001). The interfaces generated by oneapi compiler for oneapi kernel are controlled by the [board_spec.xml file](https://ofs.github.io/ofs-2024.2-1/hw/common/reference_manual/oneapi_asp/oneapi_asp_ref_mnl/#21-board_specxml-file) for board variant being compiled.
> 
> The reference oneapi-asp design is explained in [this](https://ofs.github.io/ofs-2024.2-1/hw/common/reference_manual/oneapi_asp/oneapi_asp_ref_mnl/#53-oneapi-asp-hardware-implementation) section. The reference code for [ofs_n6001 board variant](https://github.com/OFS/oneapi-asp/tree/master/n6001/hardware/ofs_n6001) interfaces with the host and on-board memory. The default n6000 FIM configuration does not have the Memory Subsystem enabled as explained [here](https://ofs.github.io/ofs-2024.2-1/hw/n6001/dev_guides/fim_dev/ug_dev_fim_ofs_n6001/#2125-memory-ofss-file). The steps to add the Memory-SS are given [here in the Shell Developer Guide](https://ofs.github.io/ofs-2024.2-1/hw/n6001/dev_guides/fim_dev/ug_dev_fim_ofs_n6001/#472-walkthrough-add-or-remove-the-memory-sub-system).
> 
> If you would like to compile for n6000, can you try generating the [PR tree for the FIM for n6000 configuration](https://ofs.github.io/ofs-2024.2-1/hw/n6001/dev_guides/fim_dev/ug_dev_fim_ofs_n6001/#225-walkthrough-compile-ofs-fim) with memory SS enabled, then using this PR build tree from FIM for building the oneapi-asp based on steps [here](https://ofs.github.io/ofs-2024.2-1/hw/common/user_guides/oneapi_asp/ug_oneapi_asp/)? ”
> 
> Thank you.
